plugins { id 'com.android.application' }

android {
    namespace 'com.soudi.beincastfix'
    compileSdk 35

    defaultConfig {
        applicationId 'com.soudi.beincastfix'
        minSdk 28
        targetSdk 35
        versionCode 3
        versionName '3.0-modern-inert'
    }
}

dependencies {
    compileOnly 'io.github.libxposed:api:102.0.0'
}
